# Generated by Django 4.2.7 on 2023-12-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinainyeccion',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('M', 'Mantenimiento')], max_length=1),
        ),
    ]
