# Generated by Django 4.2.7 on 2023-12-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0007_tipoproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
