# Generated by Django 4.2.7 on 2024-05-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0014_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelEncoderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('categoria', models.CharField(max_length=150)),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
