# Generated by Django 4.2.7 on 2024-08-20 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0015_labelencodertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_fabri', models.CharField(max_length=8, unique=True)),
                ('cantidad_fabric', models.IntegerField()),
                ('rechaz_no_ok', models.IntegerField(default=20)),
                ('extra_ok', models.IntegerField(default=1)),
                ('largo', models.FloatField()),
                ('ancho', models.FloatField()),
                ('mp_kg', models.FloatField()),
                ('aditi_kg', models.FloatField()),
                ('merma_gr', models.FloatField()),
                ('ciclo_seg', models.FloatField()),
                ('c_molde_macho', models.FloatField()),
                ('c_molde_hembra', models.FloatField()),
                ('c_product', models.FloatField()),
                ('peso_gr_prensad', models.FloatField()),
                ('zona_1', models.FloatField()),
                ('zona_2', models.FloatField()),
                ('zona_3', models.FloatField()),
                ('zona_4', models.FloatField()),
                ('zona_5', models.FloatField()),
                ('operario', models.IntegerField()),
                ('responsable', models.IntegerField()),
                ('color', models.IntegerField()),
                ('aditivo', models.IntegerField()),
                ('prediccion', models.FloatField()),
                ('v_real', models.FloatField(blank=True, null=True)),
                ('estado', models.BooleanField()),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.maquinainyeccion')),
                ('mp_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.materiaprima')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.producto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.tipoproducto')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.turno')),
            ],
        ),
    ]
