# Generated by Django 4.2.7 on 2024-08-26 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0017_alter_prediccion_aditivo_alter_prediccion_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediccion',
            name='estado',
        ),
        migrations.AddField(
            model_name='prediccion',
            name='fecha_produccion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
