# Generated by Django 4.2.7 on 2024-10-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0018_remove_prediccion_estado_prediccion_fecha_produccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_fabricada', models.IntegerField()),
                ('rechazadas', models.IntegerField()),
                ('operario', models.CharField(max_length=100)),
                ('responsable_calidad', models.CharField(max_length=100)),
                ('producto', models.CharField(max_length=100)),
                ('tipo_producto', models.CharField(max_length=100)),
                ('maquina', models.CharField(max_length=50)),
                ('molde_macho', models.IntegerField()),
                ('molde_hembra', models.IntegerField()),
                ('c_producto', models.IntegerField()),
                ('peso', models.FloatField()),
                ('zona_1', models.IntegerField()),
                ('zona_2', models.IntegerField()),
                ('zona_3', models.IntegerField()),
                ('zona_4', models.IntegerField()),
                ('zona_5', models.IntegerField()),
            ],
        ),
    ]
