# Generated by Django 4.2.7 on 2024-10-08 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0020_detalleprediccion_prediccionv2_delete_prediccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccionv2',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
