# Generated by Django 4.2.7 on 2024-10-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0021_alter_prediccionv2_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccionv2',
            name='prediccion_promedio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
