# Generated by Django 4.2.7 on 2024-10-18 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0022_prediccionv2_prediccion_promedio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operario', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=255)),
                ('maquina', models.CharField(max_length=255)),
                ('temp_molde_macho', models.FloatField()),
                ('temp_molde_hembra', models.FloatField()),
                ('zona_1', models.FloatField()),
                ('zona_2', models.FloatField()),
                ('zona_3', models.FloatField()),
                ('zona_4', models.FloatField()),
                ('zona_5', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('prediccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.prediccionv2')),
            ],
        ),
    ]
