# Generated by Django 4.2.7 on 2024-10-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0025_recomendacion_temp_c_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccionv2',
            name='peso_prensada',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=5),
        ),
    ]
